import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="ko">
      <title>thecorative</title>
      <body>
        <div className="navBar">
          <Link href="/">
            <Image src="/images/logo.png" width={170} height={33} alt="logo" />
          </Link>
          <div className="linkBar">
            <Link href="/">Home</Link>
            <Link href="/list">Blog</Link>
            <Link href="/list">Portfolio</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
