import "./globals.css";
import Link from "next/link";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="ko">
      <title>thecorative</title>
      <body>
        <div className="navBar">
          <Link href="/">thecorativeBlog</Link>

          <Link href="/list">Blog</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
