import { getServerSession } from "next-auth";
import LoginButton from "./Style/LoginButton";
import "./globals.css";
import Link from "next/link";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await getServerSession(authOptions);

  return (
    <html lang="ko">
      <title>thecorative</title>
      <body>
        <div className="navBar">
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <LoginButton />
        </div>
        {children}
      </body>
    </html>
  );
}
